set_property IOSTANDARD LVCMOS33 [get_ports {y_bo[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y_bo[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y_bo[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y_bo[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y_bo[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y_bo[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y_bo[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y_bo[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y_bo[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y_bo[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y_bo[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y_bo[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y_bo[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y_bo[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y_bo[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {y_bo[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {a_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_i[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_i[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_i[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {b_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_i[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_i[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_i[0]}]

set_property PACKAGE_PIN R13 [get_ports {b_i[7]}]
set_property PACKAGE_PIN U18 [get_ports {b_i[6]}]
set_property PACKAGE_PIN T18 [get_ports {b_i[5]}]
set_property PACKAGE_PIN R17 [get_ports {b_i[4]}]
set_property PACKAGE_PIN R15 [get_ports {b_i[3]}]
set_property PACKAGE_PIN M13 [get_ports {b_i[2]}]
set_property PACKAGE_PIN L16 [get_ports {b_i[1]}]
set_property PACKAGE_PIN J15 [get_ports {b_i[0]}]

set_property PACKAGE_PIN V10 [get_ports {a_i[7]}]
set_property PACKAGE_PIN U11 [get_ports {a_i[6]}]
set_property PACKAGE_PIN U12 [get_ports {a_i[5]}]
set_property PACKAGE_PIN H6 [get_ports {a_i[4]}]
set_property PACKAGE_PIN T13 [get_ports {a_i[3]}]
set_property PACKAGE_PIN R16 [get_ports {a_i[2]}]
set_property PACKAGE_PIN U8 [get_ports {a_i[1]}]
set_property PACKAGE_PIN T8 [get_ports {a_i[0]}]

set_property PACKAGE_PIN V11 [get_ports {y_bo[15]}]
set_property PACKAGE_PIN V12 [get_ports {y_bo[14]}]
set_property PACKAGE_PIN V14 [get_ports {y_bo[13]}]
set_property PACKAGE_PIN V15 [get_ports {y_bo[12]}]
set_property PACKAGE_PIN T16 [get_ports {y_bo[11]}]
set_property PACKAGE_PIN U14 [get_ports {y_bo[10]}]
set_property PACKAGE_PIN T15 [get_ports {y_bo[9]}]
set_property PACKAGE_PIN V16 [get_ports {y_bo[8]}]
set_property PACKAGE_PIN U16 [get_ports {y_bo[7]}]
set_property PACKAGE_PIN U17 [get_ports {y_bo[6]}]
set_property PACKAGE_PIN V17 [get_ports {y_bo[5]}]
set_property PACKAGE_PIN R18 [get_ports {y_bo[4]}]
set_property PACKAGE_PIN N14 [get_ports {y_bo[3]}]
set_property PACKAGE_PIN J13 [get_ports {y_bo[2]}]
set_property PACKAGE_PIN K15 [get_ports {y_bo[1]}]
set_property PACKAGE_PIN H17 [get_ports {y_bo[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports busy_o]
set_property IOSTANDARD LVCMOS33 [get_ports clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports rst_i]
set_property IOSTANDARD LVCMOS33 [get_ports start_i]

set_property PACKAGE_PIN G14 [get_ports busy_o]
set_property PACKAGE_PIN P17 [get_ports start_i]
set_property PACKAGE_PIN M17 [get_ports rst_i]
set_property PACKAGE_PIN E3 [get_ports clk_i]

create_clock -period 10.000 -name clk -waveform {0.000 5.000} -add [get_ports clk_i]

set_property SLEW SLOW [get_ports {y_bo[15]}]
set_property SLEW SLOW [get_ports {y_bo[14]}]
set_property SLEW SLOW [get_ports {y_bo[13]}]
set_property SLEW SLOW [get_ports {y_bo[12]}]
set_property SLEW SLOW [get_ports {y_bo[11]}]
set_property SLEW SLOW [get_ports {y_bo[10]}]
set_property SLEW SLOW [get_ports {y_bo[9]}]
set_property SLEW SLOW [get_ports {y_bo[8]}]
set_property SLEW SLOW [get_ports {y_bo[7]}]
set_property SLEW SLOW [get_ports {y_bo[6]}]
set_property SLEW SLOW [get_ports {y_bo[5]}]
set_property SLEW SLOW [get_ports {y_bo[4]}]
set_property SLEW SLOW [get_ports {y_bo[3]}]
set_property SLEW SLOW [get_ports {y_bo[2]}]
set_property SLEW SLOW [get_ports {y_bo[1]}]
set_property SLEW SLOW [get_ports {y_bo[0]}]
